### ISSUE TITLE
Only works on URLs ending in an image extension

### ISSUE THREAD

**Issue by TheLounger** [msujaws/transparent-standalone-images#2]
For example, it doesn't work on a URL like this:
https://github.com/fluidicon.png?a=b
Adding a `*` at the end of the `matches` resolves this problem.

Isn't it possible to match mimetypes instead of URLs?
Then things like this would even work:
`http://www.example.com/generate_png_img.php?img=abc`

**Comment by msujaws** [comment]
Adding the * at the end of the matches would run this code on every website.

I'd prefer if we didn't have to do that. I'll see if there is a way to filter on mimetypes instead of URLs.

**Comment by msujaws** [comment]
I posted a question in the #extdev room on IRC about this.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts doesn't show a way to do this with content_scripts.

**Comment by msujaws** [comment]
This is now fixed in https://github.com/msujaws/transparent-standalone-images/commit/60e20ad1556a61aef934bc2c480ce30e3c44d4da

**Comment by msujaws** [comment]
This is now fixed in version 2.1 of the add-on. If you have it installed it should update automatically.
